import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

df = pd.read_csv("Data/cleaned_reviews.csv")

# We used this to check the cleaned reviews and the features generated by TF-IDF.
# We can uncomment these lines if we want to inspect the data again.

# print(df.head())
# print(df.columns)

X = df["clean_review"]
y = df["sentiment"]

print(y.value_counts())

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training Distribution")
print(y_train.value_counts(normalize=True))

print("\nTesting Distribution")
print(y_test.value_counts(normalize=True))

print("Training Set")
print(y_train.value_counts())

print("\nTesting Set")
print(y_test.value_counts())

vectorizer = TfidfVectorizer(
    stop_words="english",
    min_df=2
)

X_train_tfidf = vectorizer.fit_transform(X_train)

X_test_tfidf = vectorizer.transform(X_test)

print("Train Shape:", X_train_tfidf.shape)
print("Test Shape:", X_test_tfidf.shape)

balanced_model = LogisticRegression(
    class_weight="balanced",
    random_state=42,
    max_iter=1000
)

# Train the model
balanced_model.fit(X_train_tfidf, y_train)

# Make predictions
balanced_pred = balanced_model.predict(
    X_test_tfidf
)

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

print("\nModel Evaluation")
print("-" * 50)

print(
    "Accuracy:",
    accuracy_score(y_test, balanced_pred)
)

print(
    "Precision:",
    precision_score(
        y_test,
        balanced_pred,
        pos_label="Negative",
        zero_division=0
    )
)

print(
    "Recall:",
    recall_score(
        y_test,
        balanced_pred,
        pos_label="Negative"
    )
)

print(
    "F1 Score:",
    f1_score(
        y_test,
        balanced_pred,
        pos_label="Negative"
    )
)

print("\nClassification Report")
print(
    classification_report(
        y_test,
        balanced_pred,
        zero_division=0
    )
)

print("\nConfusion Matrix")
print(confusion_matrix(y_test, balanced_pred))




results = pd.DataFrame({
    "review": X_test,
    "actual": y_test,
    "predicted": balanced_pred
})

errors = results[
    results["actual"] != results["predicted"]
]

print("\nMisclassified Reviews")
print(errors.head(20))


feature_names = vectorizer.get_feature_names_out()

coefficients = balanced_model.coef_[0]

top_positive = coefficients.argsort()[-20:]
top_negative = coefficients.argsort()[:20]

print("\nTop Positive Words")
for idx in reversed(top_positive):
    print(feature_names[idx], coefficients[idx])

print("\nTop Negative Words")
for idx in top_negative:
    print(feature_names[idx], coefficients[idx])